### ISSUE TITLE
Debugging command is mispelled

### ISSUE THREAD

**Issue by wjgeorge** [movabletype/Documentation#3]
In https://github.com/movabletype/Documentation/wiki/English-plugin-dev-2-4

debugging is is invoked via $DB::single = 1  NOT $DB::signal=1

**Comment by CNG** [comment]
I haven't used these extensively, but from glancing at Perl's `DB.pm`, it appears you're correct, so I'll make the change:

```
  $DB::single = 0;      # single-step flag (set it to 1 to enable stops in BEGIN/use)
  $DB::signal = 0;      # signal flag (will cause a stop at the next line)
```

Thank you!

**Comment by yuji** [comment]
Hey guys, Thanks!
